### ISSUE TITLE
Unclear steps in Readme

### ISSUE THREAD

**Issue by tawandamoyo** [unicef/publicgoods-wordpress#2]
Step 3 is unclear. The instruction is to change folders into `publicgoods-wordpress`, yet the code snippet below the instruction is:

``` 
cd publicgoods-candidates
git pull --rebase
./develop.bash

```

Is it the same step? Got stuck there

**Comment by lacabra** [comment]
Hi @tawandamoyo! 

Thanks for your interest in our work on digital public goods, and apologies for the delay in getting back to you, as I was out of the office the entire last week. I have amended the documentation correcting the discrepancy that you pointed out.

Let me know if anything else is not clear. Alternatively, join our [chat](https://app.element.io/#/room/#unicef-innovation:mozilla.org) for a real-time conversation.
